"""empty message

Revision ID: 0a6279efb9ba
Revises: 964696de8c93
Create Date: 2017-09-14 09:45:05.576000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6279efb9ba'
down_revision = '964696de8c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_type', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('course_type', sa.Column('create_user', sa.String(), nullable=True))
    op.add_column('course_type', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('course_type', sa.Column('update_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_type', 'update_user')
    op.drop_column('course_type', 'update_time')
    op.drop_column('course_type', 'create_user')
    op.drop_column('course_type', 'create_time')
    # ### end Alembic commands ###
