"""empty message

Revision ID: 74429142dd36
Revises: c685b26a3521
Create Date: 2017-09-19 13:41:10.999000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74429142dd36'
down_revision = 'c685b26a3521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('base', sa.Boolean(), nullable=True))
    op.drop_column('student', 'basis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('basis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('student', 'base')
    # ### end Alembic commands ###
