"""empty message

Revision ID: 8766635377ad
Revises: 88533594745b
Create Date: 2017-09-11 14:36:42.691000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8766635377ad'
down_revision = '88533594745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', sa.Integer(), nullable=True))
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('role', 'permission')
    # ### end Alembic commands ###
