"""empty message

Revision ID: 88533594745b
Revises: b2fa593ad64a
Create Date: 2017-09-11 11:25:16.432000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88533594745b'
down_revision = 'b2fa593ad64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
