"""empty message

Revision ID: 972a0e50bdd5
Revises: 0927fe7ee9ad
Create Date: 2017-08-25 09:16:30.444000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972a0e50bdd5'
down_revision = '0927fe7ee9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
