"""empty message

Revision ID: b46db643a9c2
Revises: c1f61b8115cb
Create Date: 2017-09-14 17:02:56.675000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46db643a9c2'
down_revision = 'c1f61b8115cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('wx', sa.String(), nullable=True),
    sa.Column('ws_name', sa.String(), nullable=True),
    sa.Column('qq', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('basis', sa.Boolean(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('id_card_image', sa.String(), nullable=True),
    sa.Column('pay_image', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
