"""empty message

Revision ID: c1f61b8115cb
Revises: 0a6279efb9ba
Create Date: 2017-09-14 09:53:55.046000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f61b8115cb'
down_revision = '0a6279efb9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
