"""empty message

Revision ID: c685b26a3521
Revises: b46db643a9c2
Create Date: 2017-09-19 13:28:25.902000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c685b26a3521'
down_revision = 'b46db643a9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('card_image_back', sa.String(), nullable=True))
    op.add_column('student', sa.Column('card_image_front', sa.String(), nullable=True))
    op.add_column('student', sa.Column('wx_name', sa.String(), nullable=True))
    op.drop_column('student', 'ws_name')
    op.drop_column('student', 'id_card_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id_card_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('ws_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student', 'wx_name')
    op.drop_column('student', 'card_image_front')
    op.drop_column('student', 'card_image_back')
    # ### end Alembic commands ###
