"""empty message

Revision ID: ceccd5587e1a
Revises: b3b2b3faa8d4
Create Date: 2017-09-19 20:24:19.472000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceccd5587e1a'
down_revision = 'b3b2b3faa8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('subject_image', sa.String(), nullable=True))
    op.drop_column('subject', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subject', 'subject_image')
    # ### end Alembic commands ###
