"""empty message

Revision ID: f25a636daddb
Revises: 16ebfafd5cd0
Create Date: 2017-08-25 16:52:14.785000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25a636daddb'
down_revision = '16ebfafd5cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('hex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'hex')
    # ### end Alembic commands ###
